# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_activo_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='potencia',
        ),
    ]
