# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-11 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_activo_potencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulonoserial',
            options={'verbose_name': 'Articulo no serial', 'verbose_name_plural': 'Articulos no seriales'},
        ),
        migrations.AlterField(
            model_name='bodega',
            name='identi',
            field=models.CharField(max_length=100, verbose_name='Identificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
