# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_auto_20160221_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Direcci\xf3n',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='GeoActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=400)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Activo')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='GeoNoSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('geoactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.GeoActivo')),
                ('noserial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ActivoNoSerial')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='geoactivo',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Zona'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Zona'),
        ),
    ]
