# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoactivo',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='geoactivo',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
