# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20160223_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geonoserial',
            options={'verbose_name': 'Geo activo no-serial', 'verbose_name_plural': 'Geo activos no-seriales'},
        ),
        migrations.AlterField(
            model_name='geoactivo',
            name='descripcion',
            field=models.TextField(max_length=400, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='geoactivo',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Direccion', verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='geonoserial',
            name='noserial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ActivoNoSerial', verbose_name='Activo no serial'),
        ),
        migrations.AlterUniqueTogether(
            name='geonoserial',
            unique_together=set([('geoactivo', 'noserial')]),
        ),
    ]
